"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";import Link from "next/link";import {JOB_STATUSES,type Job} from "@jobtrackr/core";import {api} from "@/lib/client";import {Cols,Resizer,useColWidths} from "@/lib/col-resize";
type DashboardJob=Job&{fitScore?:number;personalizedJobContextScore?:number|null};
const COLUMNS=[{key:"company",label:"Company"},{key:"jobTitle",label:"Position"},{key:"location",label:"Location"},{key:"jobType",label:"Job Type"},{key:"salaryRange",label:"Salary"},{key:"fitScore",label:"Fit"},{key:"personalizedJobContextScore",label:"Context"},{key:"dateAdded",label:"Added"},{key:"status",label:"Status"}];
const COL_DEFAULTS=[40,170,260,190,120,180,70,80,100,130,68];
function daysSince(date:string|null){if(!date)return"—";const days=Math.floor((Date.now()-new Date(date).getTime())/86400000);return days<0?"—":`${days}d`}
function monogram(company:string){const words=company.replace(/\(.*\)/,"").trim().split(/\s+/);return words.length>1?(words[0][0]+words[1][0]).toUpperCase():company.slice(0,2).replace(/^(.)(.)/,(_,a,b)=>a.toUpperCase()+b.toLowerCase())}
const RAIL_STAGES=[{key:"Saved",label:"SAVED"},{key:"Applied",label:"APPLIED"},{key:"Assessment",label:"ASSESS"},{key:"Interview",label:"INTVW"},{key:"Offer",label:"OFFER"}] as const;
export default function Dashboard(){const[jobs,setJobs]=useState<DashboardJob[]>([]);const[search,setSearch]=useState("");const[status,setStatus]=useState("");const[sort,setSort]=useState("dateAdded");const[dir,setDir]=useState<"asc"|"desc">("desc");const[selected,setSelected]=useState<Set<number>>(new Set());const[notice,setNotice]=useState<string|null>(null);const[syncing,setSyncing]=useState(false);const[syncProgress,setSyncProgress]=useState<{processed:number;total:number;created:number;errors:number}|null>(null);const syncPollRef=useRef<number|undefined>(undefined);const{widths,startResize,resetCol}=useColWidths("cols:jobs",COL_DEFAULTS);
const load=useCallback(async()=>{const params=new URLSearchParams();if(search)params.set("search",search);if(status)params.set("status",status);params.set("sort",sort);params.set("dir",dir);const data=await api<{jobs:DashboardJob[]}>(`/api/jobs?${params}`);setJobs(data.jobs)},[search,status,sort,dir]);useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t)},[load]);
const stats=useMemo(()=>{const by=(s:string)=>jobs.filter(j=>j.status===s).length;const counts=Object.fromEntries(RAIL_STAGES.map(s=>[s.key,by(s.key)]));const closed=by("Rejected")+by("Withdrawn");return{counts,closed,inPlay:jobs.length-closed,total:jobs.length}},[jobs]);
function toggleSort(key:string){if(sort===key)setDir(dir==="asc"?"desc":"asc");else{setSort(key);setDir("desc")}}function toggleSelect(id:number){const next=new Set(selected);if(next.has(id))next.delete(id);else next.add(id);setSelected(next)}async function setJobStatus(id:number,newStatus:string){await api(`/api/jobs/${id}`,{method:"PATCH",json:{status:newStatus}});load()}async function bulk(action:string,extra:Record<string,string>={}){if(!selected.size)return;if(action==="delete"&&!confirm(`Delete ${selected.size} job(s)?`))return;await api("/api/jobs/bulk",{method:"POST",json:{ids:[...selected],action,...extra}});setSelected(new Set());load()}
const pollSync=useCallback(async()=>{try{const r=await api<{syncing:boolean;state:{processed:number;total:number;errors:string[]}|null;result:{processed:number;total:number;created:number;errors:string[];done:boolean}|null;error:{error:string}|null}>("/api/gmail/sync");if(r.state)setSyncProgress({processed:r.state.processed,total:r.state.total,created:r.result?.created??0,errors:r.state.errors?.length??0});else if(r.result)setSyncProgress({processed:r.result.processed,total:r.result.total,created:r.result.created,errors:r.result.errors.length});setSyncing(r.syncing);if(!r.syncing&&r.result?.done){setNotice(r.result.errors.length?`Gmail sync completed with ${r.result.errors.length} error(s). Imported ${r.result.created} job(s).`:`Gmail sync completed. Imported ${r.result.created} job(s).`);load();return true}if(r.error&&!r.syncing)setNotice(r.error.error)}catch(e){if(!syncing)setNotice(e instanceof Error?e.message:"Sync status unavailable")}return false},[load,syncing]);
useEffect(()=>{void pollSync()},[pollSync]);useEffect(()=>{if(syncing){if(syncPollRef.current)window.clearInterval(syncPollRef.current);syncPollRef.current=window.setInterval(()=>void pollSync(),500)}else if(syncPollRef.current){window.clearInterval(syncPollRef.current);syncPollRef.current=undefined}return()=>{if(syncPollRef.current)window.clearInterval(syncPollRef.current)}},[syncing,pollSync]);
useEffect(()=>{let stopped=false;let timer:number|undefined;const poll=async()=>{try{const r=await api<{running:boolean;state:{processed:number;total:number;updated:number;errors:string[]}|null;result:{processed:number;total:number;updated:number;errors:string[];done:boolean}|null;error:{error:string}|null}>("/api/jobs/repair",{method:"POST"});if(!r.running&&r.result?.done){if(r.result.updated>0)load();return}if(!stopped)timer=window.setTimeout(poll,1000)}catch{}};void poll();return()=>{stopped=true;if(timer)window.clearTimeout(timer)}},[load]);
async function syncNow(){if(syncing)return;setNotice(null);setSyncProgress({processed:0,total:0,created:0,errors:0});try{await api("/api/gmail/sync",{method:"POST"});setSyncing(true);await pollSync()}catch(err){setNotice(err instanceof Error?err.message:"Sync failed")}}
return <div className="dashboard-wide" style={{width:"calc(100vw - 48px)",maxWidth:"none",marginLeft:"calc(24px - max(0px, (100vw - 1520px)/2))"}}><div className="row" style={{marginBottom:4}}><div className="hero"><div className="eyebrow">Pipeline</div><div className="big">{stats.inPlay} in play <span className="muted" style={{fontSize:14,fontWeight:500}}>· {stats.total} total</span></div></div><div className="spacer"/><button className="btn" onClick={syncNow} disabled={syncing}>{syncing?"Syncing…":"Sync Gmail"}</button><Link href="/add" className="btn primary hide-sm" style={{display:"inline-block"}}>+ Add Job</Link></div>{notice&&<div className="notice ok">{notice}</div>}{syncProgress&&syncing&&<div className="notice" style={{marginTop:8}}>Gmail sync: {syncProgress.processed}/{syncProgress.total} messages · {syncProgress.created} jobs imported{syncProgress.errors?` · ${syncProgress.errors} errors`:""}</div>}
<div className="rail"><div className="track">{RAIL_STAGES.map((s,i)=><span key={s.key} style={{display:"contents"}}>{i>0&&<span className="seg"/>}<span className={`node ${stats.counts[s.key]>0?"lit":"zero"}`}><span className="ct">{stats.counts[s.key]}</span><span className="pip"/><span className="nm">{s.label}</span></span></span>)}</div>{stats.closed>0&&<div className="closed">+{stats.closed} CLOSED</div>}</div>
<div className="toolbar"><input type="text" placeholder="Search company, title, location…" value={search} onChange={e=>setSearch(e.target.value)} style={{flex:1,minWidth:150}}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{JOB_STATUSES.map(s=><option key={s}>{s}</option>)}</select>{selected.size>0&&<><span className="muted">{selected.size} selected</span><select defaultValue="" onChange={e=>{if(e.target.value)bulk("updateStatus",{status:e.target.value});e.target.value=""}}><option value="" disabled>Set status…</option>{JOB_STATUSES.map(s=><option key={s}>{s}</option>)}</select><button className="btn danger" onClick={()=>bulk("delete")}>Delete</button></>}</div>
<div className="jobcards">{jobs.map(j=><div className="jobcard" key={j.id}><Link href={`/jobs/${j.id}`} className="mono-tile">{monogram(j.company)}</Link><Link href={`/jobs/${j.id}`} style={{minWidth:0}}><div className="co">{j.company}</div><div className="role">{j.jobTitle}</div><div className="meta">{(j.location??"—").toUpperCase()}{j.jobType&&<> {" · "}<b>{j.jobType}</b></>}{j.salaryRange&&<> {" · "}<b>{j.salaryRange.replace(/\(.*\)/,"").trim()}</b></>} {" · "}{daysSince(j.dateApplied??j.dateAdded)}</div><div className="meta" style={{marginTop:5}}><b>Fit {typeof j.fitScore==="number"?j.fitScore:"—"}</b>{" · "}<b>Context {typeof j.personalizedJobContextScore==="number"?j.personalizedJobContextScore:"—"}</b></div></Link><select value={j.status} onChange={e=>setJobStatus(j.id,e.target.value)} className={`stamp ${j.status}`} aria-label={`Status for ${j.company}`}>{!JOB_STATUSES.includes(j.status as (typeof JOB_STATUSES)[number])&&<option>{j.status}</option>}{JOB_STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>)}{!jobs.length&&<div className="card muted" style={{textAlign:"center"}}>No applications yet — tap + to add your first one.</div>}</div>
<div className="table-wrap jobs-table" style={{width:"100%",overflowX:"auto"}}><table className="fixed" style={{minWidth:1400}}><Cols widths={widths}/><thead><tr><th style={{cursor:"default"}}><input type="checkbox" checked={selected.size>0&&selected.size===jobs.length} onChange={e=>setSelected(e.target.checked?new Set(jobs.map(j=>j.id)):new Set())}/><Resizer i={0} startResize={startResize} resetCol={resetCol}/></th>{COLUMNS.map((c,ci)=><th key={c.key} onClick={()=>toggleSort(c.key)}>{c.label} {sort===c.key?(dir==="asc"?"↑":"↓"):""}<Resizer i={ci+1} startResize={startResize} resetCol={resetCol}/></th>)}<th style={{cursor:"default"}}>Days</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><input type="checkbox" checked={selected.has(j.id)} onChange={()=>toggleSelect(j.id)}/></td><td><Link href={`/jobs/${j.id}`}>{j.company}</Link></td><td title={j.jobTitle}>{j.jobTitle}</td><td title={j.location??undefined}>{j.location??"—"}</td><td>{j.jobType||"?"}</td><td title={j.salaryRange??undefined}>{j.salaryRange??"—"}</td><td>{typeof j.fitScore==="number"?j.fitScore:"—"}</td><td>{typeof j.personalizedJobContextScore==="number"?j.personalizedJobContextScore:"—"}</td><td>{j.dateAdded}</td><td><select value={j.status} onChange={e=>setJobStatus(j.id,e.target.value)} className={`stamp ${j.status}`} aria-label={`Status for ${j.company}`}>{!JOB_STATUSES.includes(j.status as (typeof JOB_STATUSES)[number])&&<option>{j.status}</option>}{JOB_STATUSES.map(s=><option key={s}>{s}</option>)}</select></td><td className="muted">{daysSince(j.dateApplied??j.dateAdded)}</td></tr>)}{!jobs.length&&<tr><td colSpan={11} className="muted" style={{textAlign:"center",padding:30}}>No applications yet — add one, capture from the extension, or import your v1 backup in Settings.</td></tr>}</tbody></table></div></div>}
