import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
const MAX_REDIRECTS=3;const MAX_RESPONSE_BYTES=2*1024*1024;
function isPrivateIp(address:string):boolean{const version=isIP(address);if(version===4){const[a,b]=address.split(".").map(Number);return a===10||a===127||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a===0}if(version===6){const n=address.toLowerCase();return n==="::1"||n==="::"||n.startsWith("fc")||n.startsWith("fd")||n.startsWith("fe8")||n.startsWith("fe9")||n.startsWith("fea")||n.startsWith("feb")}return false}
async function assertSafeUrl(rawUrl:string):Promise<URL>{let url:URL;try{url=new URL(rawUrl)}catch{throw new Error("Invalid job posting URL")}if(!["http:","https:"].includes(url.protocol))throw new Error("Only HTTP(S) job posting URLs are supported");if(url.username||url.password)throw new Error("Job posting URL must not contain credentials");if(url.port&&!['80','443'].includes(url.port))throw new Error("Job posting URL must use HTTP or HTTPS standard ports");const hostname=url.hostname.toLowerCase().replace(/^\[|\]$/g,"");if(hostname==="localhost"||hostname.endsWith(".localhost")||hostname.endsWith(".local")||hostname.endsWith(".internal"))throw new Error("Local/private job posting URLs are not allowed");if(isPrivateIp(hostname))throw new Error("Private or loopback job posting URLs are not allowed");try{const records=await lookup(hostname,{all:true,verbatim:true});if(!records.length||records.some(r=>isPrivateIp(r.address)))throw new Error("Private or loopback job posting URLs are not allowed")}catch(err){if(err instanceof Error&&err.message.includes("Private or loopback"))throw err;throw new Error("Could not resolve the job posting host")}return url}
async function fetchSafe(rawUrl:string):Promise<{url:string;html:string}> {let current=await assertSafeUrl(rawUrl);for(let redirects=0;redirects<=MAX_REDIRECTS;redirects++){const res=await fetch(current,{headers:{"user-agent":"Mozilla/5.0 (compatible; JobTrackr/2.0)",accept:"text/html,application/xhtml+xml"},redirect:"manual",signal:AbortSignal.timeout(15000)});if(res.status>=300&&res.status<400){if(redirects===MAX_REDIRECTS)throw new Error("Too many redirects while fetching the job posting");const location=res.headers.get("location");if(!location)throw new Error("Job posting returned an invalid redirect");current=await assertSafeUrl(new URL(location,current).toString());continue}if(!res.ok)throw new Error(`Fetching the URL failed (HTTP ${res.status})`);const length=Number(res.headers.get("content-length")??0);if(length>MAX_RESPONSE_BYTES)throw new Error("Job posting response is too large (2 MB maximum)");const html=await res.text();if(Buffer.byteLength(html,"utf8")>MAX_RESPONSE_BYTES)throw new Error("Job posting response is too large (2 MB maximum)");return{url:current.toString(),html}}throw new Error("Unable to fetch job posting")}
function htmlToText(html:string):string{return html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<\/(?:p|div|section|article|li|h[1-6]|br|tr)>/gi,"\n").replace(/<[^>]+>/g," ").replace(/&nbsp;|&amp;|&#\d+;/g," ").replace(/[ \t]+/g," ").replace(/\n\s*\n+/g,"\n\n").trim()}
function extractAboutTheJob(text:string):string|null{const normalized=text.replace(/\r/g,"");const match=normalized.match(/(?:^|\n)\s*About the Job\s*[:\-]?\s*\n([\s\S]*?)(?=\n\s*(?:About the company|Benefits|Qualifications|Requirements|Skills|Responsibilities|What you(?:'|’)ll do|How you(?:'|’)ll make an impact|Apply|See more|Show less)\b|$)/i);return match?.[1]?.trim()||null}
function looksClosed(text:string):boolean{return /no longer (accepting|available)|position (has )?(been )?(filled|closed)|job (is )?closed|this job (is )?no longer available|applications? (are )?closed|role (has )?been filled|we('re| are) no longer accepting/i.test(text)}
export async function fetchJobPosting(url:string):Promise<{url:string;content:string;open:boolean}>{const fetched=await fetchSafe(url);const html=fetched.html;const text=htmlToText(html);const about=extractAboutTheJob(text);const jsonLdBlocks=[...html.matchAll(/<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)];for(const m of jsonLdBlocks){try{const data=JSON.parse(m[1]);const items=Array.isArray(data)?data:[data];const posting=items.find((i:any)=>i?.["@type"]==="JobPosting");if(posting){const status=String(posting.validThrough??"");const closing=String(posting.jobStatus??"");const closed=looksClosed(JSON.stringify(posting))||/closed|filled|expired/i.test(closing)||(status&&Date.parse(status)<Date.now());const structured=`URL: ${fetched.url}\nJSON-LD JobPosting:\n${JSON.stringify(posting).slice(0,30000)}`;return{url:fetched.url,content:about?`${structured}\nABOUT_THE_JOB_VERBATIM:\n${about.slice(0,30000)}`:structured,open:!closed}}}catch{}}
if(text.length<200)throw new Error("The page returned too little readable content (it may require JavaScript or block bots). Paste the posting text instead.");return{url:fetched.url,content:about?`URL: ${fetched.url}\nABOUT_THE_JOB_VERBATIM:\n${about.slice(0,30000)}\nPage text:\n${text.slice(0,30000)}`:`URL: ${fetched.url}\nPage text:\n${text.slice(0,30000)}`,open:!looksClosed(text)}}
export async function fetchUrlContent(url:string):Promise<string>{const result=await fetchJobPosting(url);if(!result.open)throw new Error("Job posting is no longer open");return result.content}
