import { CATEGORY_TO_STATUS, TERMINAL_STATUSES, type JobStatus } from "@jobtrackr/core";
import { classifyEmail, aiAvailable, parseJobPostings, personalizeJob } from "./ai";
import { getDb, getSetting, setSetting } from "./db";
import { createJob, findDuplicate, listJobs, matchJobForEmail, shouldAutoApply, updateJob } from "./jobs";
import { fetchJobPosting } from "./fetch-job";
const TOKEN_URL="https://oauth2.googleapis.com/token";const GMAIL_API="https://gmail.googleapis.com/gmail/v1/users/me";const BATCH_SIZE=5;const MAX_MESSAGES=10000;
function creds(){const clientId=process.env.GOOGLE_CLIENT_ID,clientSecret=process.env.GOOGLE_CLIENT_SECRET;return clientId&&clientSecret?{clientId,clientSecret}:null}
function labelName(){const label=(process.env.GMAIL_LABEL||"LinkedIn").trim();if(!label)throw new Error("GMAIL_LABEL is empty");return label}
async function accessToken(){const t=getSetting<any>("gmailTokens");if(!t)throw new Error("Gmail is not connected");if(Date.now()<t.expires_at-60000)return t.access_token;const c=creds();if(!c||!t.refresh_token)throw new Error("Gmail token expired and cannot be refreshed — reconnect Gmail");const r=await fetch(TOKEN_URL,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:t.refresh_token,grant_type:"refresh_token"})});if(!r.ok)throw new Error(`Token refresh failed: ${await r.text()}`);const d=await r.json() as any;const updated={...t,access_token:d.access_token,expires_at:Date.now()+d.expires_in*1000};setSetting("gmailTokens",updated);return updated.access_token}
async function gmailGet(path:string):Promise<any>{const r=await fetch(`${GMAIL_API}${path}`,{headers:{authorization:`Bearer ${await accessToken()}`}});if(!r.ok)throw new Error(`Gmail API ${r.status}: ${await r.text()}`);return await r.json()}
function decode(data:string){return Buffer.from(data.replaceAll("-","+").replaceAll("_","/"),"base64").toString("utf8")}
function body(p:any):string{if(p.mimeType==="text/plain"&&p.body?.data)return decode(p.body.data);if(p.parts)for(const x of p.parts){const v=body(x);if(v)return v}if(p.body?.data)return decode(p.body.data);return ""}
function header(h:any[],n:string){return h.find(x=>x.name.toLowerCase()===n.toLowerCase())?.value??""}
function urls(text:string):string[]{return [...new Set((text.match(/https?:\/\/[^\s<>"']+/g)||[]).map(u=>u.replace(/[),.;]+$/g,"")))]}
function senderDomain(from:string){const at=from.lastIndexOf("@");return at>=0?from.slice(at+1).split(">")[0].trim():null}
async function resolveLabelId(name:string){const d=await gmailGet("/labels");const labels=d.labels??[];const exact=labels.find((x:any)=>x.name===name)||labels.find((x:any)=>x.name.toLowerCase()===name.toLowerCase());if(exact)return exact.id;throw new Error(`Gmail label not found: ${name}`)}
async function collect(labelId:string){const params=new URLSearchParams({labelIds:labelId,maxResults:"100",includeSpamTrash:"false"});const all:any[]=[];let token="";for(let page=0;page<100;page++){const p=new URLSearchParams(params);if(token)p.set("pageToken",token);const d=await gmailGet(`/messages?${p.toString()}`);all.push(...(d.messages??[]));token=d.nextPageToken??"";if(!token||all.length>=MAX_MESSAGES)break}return all.slice(0,MAX_MESSAGES)}
function saveState(s:unknown){setSetting("gmailSyncState",s)}export function getGmailSyncState(){return getSetting("gmailSyncState")}
export async function syncGmailBatch(){if(!aiAvailable())throw new Error("AI provider is not configured — email classification needs an available provider");const label=labelName();const labelId=await resolveLabelId(label);let state=getSetting<any>("gmailSyncState");if(!state||!Array.isArray(state.queue)||state.queue.length===0){const queue=await collect(labelId);state={queue,processed:0,total:queue.length,errors:[],startedAt:new Date().toISOString()};saveState(state)}const db=getDb();const profile=getSetting<any>("profile");const result:any={scanned:0,classified:0,linked:0,created:0,personalized:0,statusUpdates:[],errors:[],label,queryMode:"labelIds",done:false,processed:state.processed,total:state.total};const trackedCompanies=listJobs().filter(j=>!TERMINAL_STATUSES.includes(j.status as JobStatus)).map(j=>j.company);const seen=new Map((db.prepare("SELECT id,gmailId,jobId FROM emails").all() as any[]).map(x=>[x.gmailId,x]));const chunk=state.queue.splice(0,BATCH_SIZE);result.scanned=chunk.length;
for(const m of chunk){try{const full=await gmailGet(`/messages/${m.id}?format=full`);const headers=full.payload?.headers??[];const from=header(headers,"From");const subject=header(headers,"Subject");const text=full.payload?body(full.payload):full.snippet||"";const messageUrls=urls(text);const configuredLabel=label.toLowerCase()==="linkedin";let postings:any[]=[];let classification:any;if(configuredLabel){try{postings=await parseJobPostings(`Subject: ${subject}\nFrom: ${from}\n\n${text}\n\nCANDIDATE_URLS:\n${messageUrls.join("\n")}`)}catch{}}if(postings.length)classification={category:"other_job_related",company:postings[0].company||null,jobTitle:postings[0].jobTitle||null,confidence:1,summary:`${postings.length} vacancy/vacancies extracted from LinkedIn email`};else{classification=await classifyEmail({from,subject,body:text,trackedCompanies});if(!configuredLabel&&classification.category==="other_job_related"){postings=await parseJobPostings(`Subject: ${subject}\nFrom: ${from}\n\n${text}\n\nCANDIDATE_URLS:\n${messageUrls.join("\n")}`)}}result.classified++;let firstJobId:number|null=null;
for(const parsed of postings){if(!parsed.company||!parsed.jobTitle)continue;let job=findDuplicate(parsed.company,parsed.jobTitle);let verified:any=null;const candidateUrl=parsed.sourceUrl||messageUrls.find((u:string)=>/linkedin\.com\/jobs|greenhouse|lever\.co|ashbyhq|workday|smartrecruiters|jobvite|bamboohr|workable/i.test(u))||null;if(!job){if(!candidateUrl){result.errors.push(`${m.id}: skipped ${parsed.jobTitle} because no job-specific URL was found`);continue}try{verified=await fetchJobPosting(candidateUrl);if(!verified.open)continue;const pageParsed=await parseJobPostings(verified.content);const exact=pageParsed.find((p:any)=>p.company?.toLowerCase()===parsed.company.toLowerCase()&&p.jobTitle?.toLowerCase()===parsed.jobTitle.toLowerCase())||pageParsed[0];if(exact){Object.assign(parsed,exact)}parsed.sourceUrl=verified.url;job=createJob({company:parsed.company,jobTitle:parsed.jobTitle,location:parsed.location,salaryRange:parsed.salaryRange,jobType:parsed.jobType,experience:parsed.experience,skills:parsed.skills,emailDomain:parsed.emailDomain??senderDomain(from),description:parsed.description,sourceUrl:verified.url,status:"Saved"},"gmail");result.created++;if(profile){try{setSetting(`jobContext:${job.id}`,await personalizeJob({job,profile}));result.personalized++}catch{}}}catch(err){result.errors.push(`${m.id}: ${parsed.jobTitle}: ${err instanceof Error?err.message:String(err)}`);continue}}if(!firstJobId)firstJobId=job.id;result.linked++}
if(!firstJobId){const linked=matchJobForEmail(senderDomain(from),classification.company==null?null:String(classification.company));if(linked){firstJobId=linked.id;result.linked++}}const suggested=(CATEGORY_TO_STATUS[classification.category as keyof typeof CATEGORY_TO_STATUS] as JobStatus|undefined)??null;if(firstJobId&&suggested&&classification.confidence>=0.75){const job=listJobs().find(j=>j.id===firstJobId);if(job&&shouldAutoApply(job.status,suggested)){updateJob(firstJobId,{status:suggested},"gmail");result.statusUpdates.push({jobId:firstJobId,company:job.company,toStatus:suggested})}}const existing=seen.get(m.id);if(existing){if(firstJobId&&existing.jobId!==firstJobId)db.prepare("UPDATE emails SET jobId=? WHERE id=?").run(firstJobId,existing.id)}else{const applied=firstJobId!==null&&result.statusUpdates.some((x:any)=>x.jobId===firstJobId)?1:0;db.prepare(`INSERT INTO emails (gmailId,threadId,jobId,fromAddress,subject,snippet,receivedAt,category,confidence,summary,suggestedStatus,statusApplied) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run(m.id,m.threadId??null,firstJobId,from,subject,(full.snippet??"").slice(0,500),full.internalDate?new Date(Number(full.internalDate)).toISOString():new Date().toISOString(),classification.category,classification.confidence,classification.summary,suggested,applied)}}catch(e){const msg=`${m.id}: ${e instanceof Error?e.message:String(e)}`;result.errors.push(msg);state.errors.push(msg)}}state.processed+=chunk.length;result.processed=state.processed;result.total=state.total;result.done=state.queue.length===0;result.errors=[...state.errors,...result.errors];if(result.done){setSetting("gmailLastSyncAt",Math.floor(Date.now()/1000));setSetting("gmailLabelSyncReady",true);setSetting("gmailHistoricalBackfillReady",true);setSetting("gmailLastSyncResult",{at:new Date().toISOString(),...result});if(result.errors.length===0)setSetting("gmailLastSuccessfulSyncResult",{at:new Date().toISOString(),...result});saveState(null)}else saveState(state);return result}
